source /opt/ros/humble/setup.bash
alias ll='ls -lah'
alias gs='git status'
alias gp='git pull'
alias dc='docker compose'
alias cls='clear'

export GCC_COLORS='error=01;31:warning=01;35'

HISTSIZE=5000
HISTFILESIZE=10000

PS1='\[\e[32m\]\u@\h:\w \$\[\e[0m\] '

export CLICOLOR=1

if [ -f ~/ros2_ws/install/setup.bash ]; then
    source ~/ros2_ws/install/setup.bash
fi

echo "[Linux Dev Setup] Environment loaded."
