# Mouse support
set -g mouse on

# Better scrolling
set -g history-limit 10000

# Split panes
bind | split-window -h
bind - split-window -v

# Reload config
bind r source-file ~/.tmux.conf

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Easier pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Status bar
set -g status-bg black
set -g status-fg green

# Enable true color
set-option -sa terminal-overrides ",xterm*:Tc"
